apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/suj007web/my-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-env   
