version: '3.8'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0711
      POSTGRES_DB: themeDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build: ./client
    ports:
      - "3001:3001"
    env_file:
      - ./client/.env
    restart: always

volumes:
  pgdata:
