apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/your-dockerhub-user/my-frontend:latest
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: frontend-env  
